export type VocabularyWord = {
  id: number
  english: string
  turkishMeanings: string[]
  englishAlternatives?: string[]
  partOfSpeech?: string
  tags: string[]
  createdAt: number | null
  example?: string
}

// IDs are permanent: existing localStorage favorites refer to these numbers.
export const words: VocabularyWord[] = [
  { id: 0, english: 'Hello', turkishMeanings: ['Merhaba'], partOfSpeech: 'interjection', tags: ['Everyday'], createdAt: null, example: 'Hello, it is nice to meet you.' },
  { id: 1, english: 'Thank you', turkishMeanings: ['Teşekkür ederim'], partOfSpeech: 'phrase', tags: ['Everyday'], createdAt: null, example: 'Thank you for your help.' },
  { id: 2, english: 'Friend', turkishMeanings: ['Arkadaş'], partOfSpeech: 'noun', tags: ['People'], createdAt: null, example: 'My friend lives near the park.' },
  { id: 3, english: 'Beautiful', turkishMeanings: ['Güzel'], partOfSpeech: 'adjective', tags: ['Everyday'], createdAt: null, example: 'This is a beautiful garden.' },
  { id: 4, english: 'Water', turkishMeanings: ['Su'], partOfSpeech: 'noun', tags: ['Food & drink'], createdAt: null, example: 'I drink water after a walk.' },
  { id: 5, english: 'Sun', turkishMeanings: ['Güneş'], partOfSpeech: 'noun', tags: ['Nature'], createdAt: null, example: 'The sun is shining today.' },
  { id: 6, english: 'Book', turkishMeanings: ['Kitap'], partOfSpeech: 'noun', tags: ['Everyday'], createdAt: null, example: 'This book tells an interesting story.' },
  { id: 7, english: 'Family', turkishMeanings: ['Aile'], partOfSpeech: 'noun', tags: ['People'], createdAt: null, example: 'My family eats dinner together.' },
  { id: 8, english: 'Coffee', turkishMeanings: ['Kahve'], partOfSpeech: 'noun', tags: ['Food & drink'], createdAt: null, example: 'I drink coffee in the morning.' },
  { id: 9, english: 'Tree', turkishMeanings: ['Ağaç'], partOfSpeech: 'noun', tags: ['Nature'], createdAt: null, example: 'There is a tall tree outside.' },
  { id: 10, english: 'Happy', turkishMeanings: ['Mutlu'], partOfSpeech: 'adjective', tags: ['Everyday'], createdAt: null, example: 'I am happy to see you.' },
  { id: 11, english: 'Bread', turkishMeanings: ['Ekmek'], partOfSpeech: 'noun', tags: ['Food & drink'], createdAt: null, example: 'We buy fresh bread every day.' },
  { id: 12, english: 'Good morning', turkishMeanings: ['Günaydın'], partOfSpeech: 'phrase', tags: ['Everyday'], createdAt: null, example: 'Good morning, how are you today?' },
  { id: 13, english: 'Teacher', turkishMeanings: ['Öğretmen'], partOfSpeech: 'noun', tags: ['People'], createdAt: null, example: 'Our teacher explains the new words.' },
  { id: 14, english: 'Sea', turkishMeanings: ['Deniz'], partOfSpeech: 'noun', tags: ['Nature'], createdAt: null, example: 'We swim in the sea in summer.' },
  { id: 15, english: 'Apple', turkishMeanings: ['Elma'], partOfSpeech: 'noun', tags: ['Food & drink'], createdAt: null, example: 'I eat an apple with my lunch.' },
  { id: 16, english: 'House', turkishMeanings: ['Ev'], partOfSpeech: 'noun', tags: ['Everyday'], createdAt: null, example: 'Their house has a small garden.' },
  { id: 17, english: 'Child', turkishMeanings: ['Çocuk'], partOfSpeech: 'noun', tags: ['People'], createdAt: null, example: 'The child is playing with a ball.' },
  { id: 18, english: 'Flower', turkishMeanings: ['Çiçek'], partOfSpeech: 'noun', tags: ['Nature'], createdAt: null, example: 'This flower smells sweet.' },
  { id: 19, english: 'Tea', turkishMeanings: ['Çay'], partOfSpeech: 'noun', tags: ['Food & drink'], createdAt: null, example: 'Would you like a cup of tea?' },
  { id: 20, english: 'Learn', turkishMeanings: ['Öğrenmek'], partOfSpeech: 'verb', tags: ['Everyday'], createdAt: null, example: 'I learn a new word every day.' },
  { id: 21, english: 'Sister', turkishMeanings: ['Kız kardeş'], partOfSpeech: 'noun', tags: ['People'], createdAt: null, example: 'My sister likes to draw.' },
  { id: 22, english: 'Rain', turkishMeanings: ['Yağmur'], partOfSpeech: 'noun', tags: ['Nature'], createdAt: null, example: 'The rain makes the streets wet.' },
  { id: 23, english: 'Goodbye', turkishMeanings: ['Hoşça kal'], partOfSpeech: 'phrase', tags: ['Everyday'], createdAt: null, example: 'Goodbye, see you tomorrow!' },
  { id: 24, english: 'School', turkishMeanings: ['Okul'], partOfSpeech: 'noun', tags: ['Everyday'], createdAt: null, example: 'I walk to school every morning.' },
  { id: 25, english: 'Read', turkishMeanings: ['Okumak'], partOfSpeech: 'verb', tags: ['Everyday'], createdAt: null, example: 'I read a book before bed.' },
  { id: 26, english: 'Write', turkishMeanings: ['Yazmak'], partOfSpeech: 'verb', tags: ['Everyday'], createdAt: null, example: 'Please write your name here.' },
  { id: 27, english: 'Mother', turkishMeanings: ['Anne'], partOfSpeech: 'noun', tags: ['People'], createdAt: null, example: 'My mother makes delicious soup.' },
  { id: 28, english: 'Mountain', turkishMeanings: ['Dağ'], partOfSpeech: 'noun', tags: ['Nature'], createdAt: null, example: 'We can see the mountain from here.' },
  { id: 29, english: 'Milk', turkishMeanings: ['Süt'], partOfSpeech: 'noun', tags: ['Food & drink'], createdAt: null, example: 'She adds milk to her coffee.' },
  {"id": 30, "english": "Run", "turkishMeanings": ["koşmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I run in the park every morning."},
  {"id": 31, "english": "Walk", "turkishMeanings": ["yürümek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "We walk to the station together."},
  {"id": 32, "english": "Eat", "turkishMeanings": ["yemek"], "partOfSpeech": "verb", "tags": ["Food & drink"], "createdAt": null, "example": "We eat dinner at seven."},
  {"id": 33, "english": "Drink", "turkishMeanings": ["içmek"], "partOfSpeech": "verb", "tags": ["Food & drink"], "createdAt": null, "example": "Please drink some water."},
  {"id": 34, "english": "Sleep", "turkishMeanings": ["uyumak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I sleep for eight hours each night."},
  {"id": 35, "english": "Wake up", "turkishMeanings": ["uyanmak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "I wake up early on weekdays."},
  {"id": 36, "english": "Get up", "turkishMeanings": ["kalkmak", "yataktan kalkmak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "I get up as soon as my alarm rings."},
  {"id": 37, "english": "Sit down", "turkishMeanings": ["oturmak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "Please sit down beside me."},
  {"id": 38, "english": "Stand up", "turkishMeanings": ["ayağa kalkmak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "We stand up when the teacher enters."},
  {"id": 39, "english": "Come", "turkishMeanings": ["gelmek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Can you come to my house tomorrow?"},
  {"id": 40, "english": "Go", "turkishMeanings": ["gitmek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I go to work by bus."},
  {"id": 41, "english": "Buy", "turkishMeanings": ["satın almak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I want to buy a new notebook."},
  {"id": 42, "english": "Sell", "turkishMeanings": ["satmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "They sell fresh fruit here."},
  {"id": 43, "english": "Pay", "turkishMeanings": ["ödemek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "You can pay by card."},
  {"id": 44, "english": "Cook", "turkishMeanings": ["yemek pişirmek", "yemek yapmak"], "partOfSpeech": "verb", "tags": ["Food & drink"], "createdAt": null, "example": "I cook dinner for my family."},
  {"id": 45, "english": "Wash", "turkishMeanings": ["yıkamak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Wash your hands before lunch."},
  {"id": 46, "english": "Clean", "turkishMeanings": ["temizlemek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "We clean the kitchen after dinner."},
  {"id": 47, "english": "Open", "turkishMeanings": ["açmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Please open the window."},
  {"id": 48, "english": "Close", "turkishMeanings": ["kapatmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Close the door when you leave."},
  {"id": 49, "english": "Listen", "turkishMeanings": ["dinlemek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I listen to music on the bus."},
  {"id": 50, "english": "Speak", "turkishMeanings": ["konuşmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Do you speak Turkish?"},
  {"id": 51, "english": "Talk", "turkishMeanings": ["konuşmak", "sohbet etmek"], "partOfSpeech": "verb", "tags": ["People"], "createdAt": null, "example": "We talk about our plans over coffee."},
  {"id": 52, "english": "Ask", "turkishMeanings": ["sormak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "You can ask me a question."},
  {"id": 53, "english": "Answer", "turkishMeanings": ["cevap vermek", "yanıtlamak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Please answer the question."},
  {"id": 54, "english": "Understand", "turkishMeanings": ["anlamak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I understand this sentence now."},
  {"id": 55, "english": "Remember", "turkishMeanings": ["hatırlamak", "anımsamak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Do you remember her name?"},
  {"id": 56, "english": "Forget", "turkishMeanings": ["unutmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Do not forget your keys."},
  {"id": 57, "english": "Help", "turkishMeanings": ["yardım etmek"], "partOfSpeech": "verb", "tags": ["People"], "createdAt": null, "example": "Can you help me carry this box?"},
  {"id": 58, "english": "Wait", "turkishMeanings": ["beklemek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "We wait for the bus here."},
  {"id": 59, "english": "Meet", "turkishMeanings": ["buluşmak"], "partOfSpeech": "verb", "tags": ["People"], "createdAt": null, "example": "We meet at the cafe every Friday."},
  {"id": 60, "english": "Visit", "turkishMeanings": ["ziyaret etmek"], "partOfSpeech": "verb", "tags": ["People"], "createdAt": null, "example": "I visit my grandparents on Sundays."},
  {"id": 61, "english": "Travel", "turkishMeanings": ["seyahat etmek", "yolculuk yapmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "We travel by train whenever possible."},
  {"id": 62, "english": "Arrive", "turkishMeanings": ["varmak", "ulaşmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "We arrive at the station at noon."},
  {"id": 63, "english": "Leave", "turkishMeanings": ["ayrılmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "We leave the office at six."},
  {"id": 64, "english": "Bring", "turkishMeanings": ["getirmek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Please bring your notebook."},
  {"id": 65, "english": "Carry", "turkishMeanings": ["taşımak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I carry my books in a bag."},
  {"id": 66, "english": "Choose", "turkishMeanings": ["seçmek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Choose a book to read."},
  {"id": 67, "english": "Need", "turkishMeanings": ["ihtiyaç duymak", "gereksinim duymak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Plants need water to grow."},
  {"id": 68, "english": "Want", "turkishMeanings": ["istemek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I want a cup of tea."},
  {"id": 69, "english": "Like", "turkishMeanings": ["sevmek", "hoşlanmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I like this song."},
  {"id": 70, "english": "Love", "turkishMeanings": ["sevmek"], "partOfSpeech": "verb", "tags": ["People"], "createdAt": null, "example": "I love my family."},
  {"id": 71, "english": "Try", "turkishMeanings": ["denemek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "Try this soup before adding salt."},
  {"id": 72, "english": "Start", "turkishMeanings": ["başlamak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "The lesson starts at nine."},
  {"id": 73, "english": "Finish", "turkishMeanings": ["bitirmek", "tamamlamak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I finish my homework before dinner."},
  {"id": 74, "english": "Work", "turkishMeanings": ["çalışmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I work in a small office."},
  {"id": 75, "english": "Study", "turkishMeanings": ["ders çalışmak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "I study for an hour after school."},
  {"id": 76, "english": "Play", "turkishMeanings": ["oynamak"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "The children play in the garden."},
  {"id": 77, "english": "Watch", "turkishMeanings": ["izlemek", "seyretmek"], "partOfSpeech": "verb", "tags": ["Everyday"], "createdAt": null, "example": "We watch a film on Saturday evenings."},
  {"id": 78, "english": "Look for", "turkishMeanings": ["aramak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "I look for my keys in my bag."},
  {"id": 79, "english": "Look after", "turkishMeanings": ["bakmak", "ilgilenmek"], "partOfSpeech": "phrasal verb", "tags": ["People"], "createdAt": null, "example": "I look after my little brother after school."},
  {"id": 80, "english": "Give up", "turkishMeanings": ["vazgeçmek", "pes etmek"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "Do not give up when a task is difficult."},
  {"id": 81, "english": "Find out", "turkishMeanings": ["öğrenmek"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "I want to find out when the shop opens."},
  {"id": 82, "english": "Turn on", "turkishMeanings": ["açmak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "Please turn on the light."},
  {"id": 83, "english": "Turn off", "turkishMeanings": ["kapatmak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "Turn off the television before bed."},
  {"id": 84, "english": "Put on", "turkishMeanings": ["giymek"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "Put on your coat before going outside."},
  {"id": 85, "english": "Take off", "turkishMeanings": ["çıkarmak"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "Take off your shoes at the door."},
  {"id": 86, "english": "Come back", "turkishMeanings": ["geri gelmek", "geri dönmek"], "partOfSpeech": "phrasal verb", "tags": ["Everyday"], "createdAt": null, "example": "Please come back before dinner."},
  {"id": 87, "english": "Grow up", "turkishMeanings": ["büyümek"], "partOfSpeech": "phrasal verb", "tags": ["People"], "createdAt": null, "example": "Children grow up quickly."},
  {"id": 88, "english": "Father", "turkishMeanings": ["baba"], "partOfSpeech": "noun", "tags": ["People"], "createdAt": null, "example": "My father enjoys cooking."},
  {"id": 89, "english": "Brother", "turkishMeanings": ["erkek kardeş"], "partOfSpeech": "noun", "tags": ["People"], "createdAt": null, "example": "My brother plays the guitar."},
  {"id": 90, "english": "Neighbor", "turkishMeanings": ["komşu"], "partOfSpeech": "noun", "tags": ["People"], "createdAt": null, "example": "Our neighbor has a friendly dog."},
  {"id": 91, "english": "Doctor", "turkishMeanings": ["doktor", "hekim"], "partOfSpeech": "noun", "tags": ["People"], "createdAt": null, "example": "The doctor asks how I feel.", "englishAlternatives": ["physician"]},
  {"id": 92, "english": "Student", "turkishMeanings": ["öğrenci"], "partOfSpeech": "noun", "tags": ["People"], "createdAt": null, "example": "Every student has a notebook."},
  {"id": 93, "english": "City", "turkishMeanings": ["şehir", "kent"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "This city has many parks."},
  {"id": 94, "english": "Street", "turkishMeanings": ["sokak"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "Our street is quiet at night."},
  {"id": 95, "english": "Road", "turkishMeanings": ["yol"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "The road leads to the village."},
  {"id": 96, "english": "Room", "turkishMeanings": ["oda"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "My room has a large window."},
  {"id": 97, "english": "Door", "turkishMeanings": ["kapı"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "Someone is waiting at the door."},
  {"id": 98, "english": "Window", "turkishMeanings": ["pencere"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "The window faces the garden."},
  {"id": 99, "english": "Table", "turkishMeanings": ["masa"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "The keys are on the table."},
  {"id": 100, "english": "Chair", "turkishMeanings": ["sandalye"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "Please take a chair."},
  {"id": 101, "english": "Bed", "turkishMeanings": ["yatak"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "The cat is sleeping on the bed."},
  {"id": 102, "english": "Bag", "turkishMeanings": ["çanta"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "My bag is full of books."},
  {"id": 103, "english": "Key", "turkishMeanings": ["anahtar"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "I cannot find my house key."},
  {"id": 104, "english": "Phone", "turkishMeanings": ["telefon"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "My phone is on the desk."},
  {"id": 105, "english": "Money", "turkishMeanings": ["para"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "I save some money every month."},
  {"id": 106, "english": "Time", "turkishMeanings": ["zaman", "vakit"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "We have enough time to walk."},
  {"id": 107, "english": "Day", "turkishMeanings": ["gün"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "Today is a sunny day."},
  {"id": 108, "english": "Week", "turkishMeanings": ["hafta"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "I exercise three times a week."},
  {"id": 109, "english": "Year", "turkishMeanings": ["yıl", "sene"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "We moved here last year."},
  {"id": 110, "english": "Morning", "turkishMeanings": ["sabah"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "I enjoy the quiet of the morning."},
  {"id": 111, "english": "Evening", "turkishMeanings": ["akşam"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "We take a walk in the evening."},
  {"id": 112, "english": "Night", "turkishMeanings": ["gece"], "partOfSpeech": "noun", "tags": ["Everyday"], "createdAt": null, "example": "The stars are bright at night."},
  {"id": 113, "english": "Breakfast", "turkishMeanings": ["kahvaltı"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "I have eggs for breakfast."},
  {"id": 114, "english": "Lunch", "turkishMeanings": ["öğle yemeği"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "We eat lunch together."},
  {"id": 115, "english": "Dinner", "turkishMeanings": ["akşam yemeği"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "Dinner is ready."},
  {"id": 116, "english": "Egg", "turkishMeanings": ["yumurta"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "I boil an egg for breakfast."},
  {"id": 117, "english": "Cheese", "turkishMeanings": ["peynir"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "This cheese tastes delicious."},
  {"id": 118, "english": "Soup", "turkishMeanings": ["çorba"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "The soup is still hot."},
  {"id": 119, "english": "Fruit", "turkishMeanings": ["meyve"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "Fresh fruit is on the table."},
  {"id": 120, "english": "Vegetable", "turkishMeanings": ["sebze"], "partOfSpeech": "noun", "tags": ["Food & drink"], "createdAt": null, "example": "A carrot is a vegetable."},
  {"id": 121, "english": "Garden", "turkishMeanings": ["bahçe"], "partOfSpeech": "noun", "tags": ["Nature"], "createdAt": null, "example": "We grow tomatoes in our garden."},
  {"id": 122, "english": "River", "turkishMeanings": ["nehir", "ırmak"], "partOfSpeech": "noun", "tags": ["Nature"], "createdAt": null, "example": "A river flows through the town."},
  {"id": 123, "english": "Forest", "turkishMeanings": ["orman"], "partOfSpeech": "noun", "tags": ["Nature"], "createdAt": null, "example": "We walked through the forest."},
  {"id": 124, "english": "Sky", "turkishMeanings": ["gökyüzü"], "partOfSpeech": "noun", "tags": ["Nature"], "createdAt": null, "example": "The sky is clear today."},
  {"id": 125, "english": "Cloud", "turkishMeanings": ["bulut"], "partOfSpeech": "noun", "tags": ["Nature"], "createdAt": null, "example": "A dark cloud covers the sun."},
  {"id": 126, "english": "Wind", "turkishMeanings": ["rüzgâr", "rüzgar"], "partOfSpeech": "noun", "tags": ["Nature"], "createdAt": null, "example": "The wind is strong this evening."},
  {"id": 127, "english": "Snow", "turkishMeanings": ["kar"], "partOfSpeech": "noun", "tags": ["Nature"], "createdAt": null, "example": "The children are playing in the snow."},
  {"id": 128, "english": "Big", "turkishMeanings": ["büyük"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "They live in a big house.", "englishAlternatives": ["large"]},
  {"id": 129, "english": "Small", "turkishMeanings": ["küçük"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "I need a small bag."},
  {"id": 130, "english": "New", "turkishMeanings": ["yeni"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "She has a new bicycle."},
  {"id": 131, "english": "Old", "turkishMeanings": ["eski"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "This old chair belonged to my grandfather."},
  {"id": 132, "english": "Hot", "turkishMeanings": ["sıcak"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "The tea is too hot to drink."},
  {"id": 133, "english": "Cold", "turkishMeanings": ["soğuk"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "The water is very cold."},
  {"id": 134, "english": "Easy", "turkishMeanings": ["kolay"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "This exercise is easy."},
  {"id": 135, "english": "Difficult", "turkishMeanings": ["zor", "güç"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "The last question was difficult."},
  {"id": 136, "english": "Fast", "turkishMeanings": ["hızlı"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "This is a fast train."},
  {"id": 137, "english": "Slow", "turkishMeanings": ["yavaş"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "We took a slow train through the mountains."},
  {"id": 138, "english": "Tired", "turkishMeanings": ["yorgun"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "I feel tired after work."},
  {"id": 139, "english": "Hungry", "turkishMeanings": ["aç"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "The children are hungry."},
  {"id": 140, "english": "Thirsty", "turkishMeanings": ["susamış"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "I am thirsty after the walk."},
  {"id": 141, "english": "Important", "turkishMeanings": ["önemli"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "This is an important decision."},
  {"id": 142, "english": "Quiet", "turkishMeanings": ["sessiz", "sakin"], "partOfSpeech": "adjective", "tags": ["Everyday"], "createdAt": null, "example": "We found a quiet place to read."},
  {"id": 143, "english": "Always", "turkishMeanings": ["her zaman", "daima"], "partOfSpeech": "adverb", "tags": ["Everyday"], "createdAt": null, "example": "I always wash my hands before eating."},
  {"id": 144, "english": "Usually", "turkishMeanings": ["genellikle", "çoğunlukla"], "partOfSpeech": "adverb", "tags": ["Everyday"], "createdAt": null, "example": "We usually eat at home."},
  {"id": 145, "english": "Sometimes", "turkishMeanings": ["bazen", "ara sıra"], "partOfSpeech": "adverb", "tags": ["Everyday"], "createdAt": null, "example": "I sometimes walk to work."},
  {"id": 146, "english": "Never", "turkishMeanings": ["asla", "hiçbir zaman"], "partOfSpeech": "adverb", "tags": ["Everyday"], "createdAt": null, "example": "I never drink coffee at night."},
  {"id": 147, "english": "Quickly", "turkishMeanings": ["hızlıca", "çabucak"], "partOfSpeech": "adverb", "tags": ["Everyday"], "createdAt": null, "example": "She quickly found her keys."},
  {"id": 148, "english": "Slowly", "turkishMeanings": ["yavaşça", "yavaş yavaş"], "partOfSpeech": "adverb", "tags": ["Everyday"], "createdAt": null, "example": "Please speak slowly."},
  {"id": 149, "english": "Together", "turkishMeanings": ["birlikte", "beraber"], "partOfSpeech": "adverb", "tags": ["People"], "createdAt": null, "example": "We study together after school."},
]
export const normalize = (value: string) => value.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ı/g, 'i')
