import {test,expect} from '@playwright/test'
async function start(page:import('@playwright/test').Page,scenario='real'){
 await page.goto('/tests/browser/aiPractice.html?scenario='+scenario)
 await page.getByRole('combobox',{name:'Tutor',exact:true}).selectOption('openai')
 await page.getByRole('button',{name:'Start practice',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('ready')
}
test('real-provider UI persists only compact outcomes and explicit selections; keyboard and mobile fit',async({page})=>{
 await page.setViewportSize({width:320,height:740});await start(page)
 await expect(page.getByText('OpenAI text tutor',{exact:true})).toBeVisible()
 await page.getByRole('textbox').fill('I would like to practice this sentence.')
 await page.getByRole('textbox').press('Tab');await page.keyboard.press('Enter')
 await expect(page.getByRole('status')).toContainText('ready')
 await page.getByRole('button',{name:'End Practice'}).click()
 await expect(page.getByRole('status')).toContainText('Practice outcomes saved')
 await expect(page.getByText('AI feedback — contextual judgments can be inaccurate.')).toBeVisible()
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('kelime-learning-state')!))
 expect(Object.values(saved.aiEvidence)).toHaveLength(1)
 expect((Object.values(saved.aiEvidence)[0] as {evaluator:string}).evaluator).toBe('openai')
 expect(JSON.stringify(saved)).not.toContain('I would like to practice this sentence.')
 expect(saved.reviewRequests).toEqual({})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
test('retry preserves the learner turn and logical identity without automatic paid calls',async({page})=>{
 await start(page,'real-retry');await page.getByRole('textbox').fill('My answer');await page.getByRole('button',{name:'Send response'}).click()
 await expect(page.getByRole('alert')).toContainText('pilot budget')
 await expect(page.getByLabel('Practice conversation').getByText('My answer',{exact:true})).toHaveCount(1)
 await page.getByRole('button',{name:'Retry tutor action'}).click();await expect(page.getByRole('status')).toContainText('ready')
 const calls=await page.evaluate(()=>(window as unknown as {practiceCalls:{requestId:string;attemptId:string;learnerIds:string[]}[]}).practiceCalls)
 expect(calls).toHaveLength(3);expect(calls[1].requestId).toBe(calls[2].requestId);expect(calls[1].attemptId).not.toBe(calls[2].attemptId);expect(calls[1].learnerIds).toEqual(calls[2].learnerIds)
 await expect(page.getByLabel('Practice conversation').getByText('My answer',{exact:true})).toHaveCount(1)
})
test('invalid final output and cancellation never save evidence',async({page})=>{
 await start(page,'real-invalid');await page.getByRole('button',{name:'End Practice'}).click();await expect(page.getByRole('alert')).toBeVisible()
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('kelime-learning-state')!).aiEvidence)).toEqual({})
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('heading',{name:'Completed quiz results'})).toBeVisible()
 await start(page,'real-cancel');await page.getByRole('textbox').fill('hello');await page.getByRole('button',{name:'Send response'}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Completed quiz results'})).toBeVisible()
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('kelime-learning-state')!).aiEvidence)).toEqual({})
})
test('Voice Answer stays local even after selecting the real tutor; unavailable guests retain mock',async({page})=>{
 await page.goto('/tests/browser/aiPractice.html?scenario=real');await page.getByRole('combobox',{name:'Tutor',exact:true}).selectOption('openai');await page.getByLabel('Practice mode').selectOption('voiceAnswer')
 await expect(page.getByText('Typed translation checked locally — no model calls')).toBeVisible();await page.getByRole('button',{name:'Start practice',exact:true}).click()
 await page.getByRole('textbox').fill('wrong');await page.getByRole('button',{name:'Send response'}).click();await page.getByRole('button',{name:'End Practice'}).click();await expect(page.getByRole('status')).toContainText('Practice outcomes saved')
 expect(await page.evaluate(()=>(window as unknown as {practiceCalls:unknown[]}).practiceCalls)).toEqual([])
 await page.goto('/tests/browser/aiPractice.html?scenario=guest');await expect(page.getByRole('combobox',{name:'Tutor',exact:true})).toHaveCount(0);await expect(page.getByText('Mock practice — no AI service connected')).toBeVisible()
})
