// Generated by npm run db:types from supabase/migrations. Do not edit manually.
import type { Json } from './models.ts'
export type Database = { public: { Tables: {
  account_records: {
    Row: {
      user_id: string
      key: string
      value: Json
      updated_at: string
      revision: number
    }
    Insert: {
      user_id: string
      key: string
      value: Json
      updated_at?: string
      revision?: number
    }
    Update: {
      user_id?: string
      key?: string
      value?: Json
      updated_at?: string
      revision?: number
    }
    Relationships: []
  }
  ai_practice_attempts: {
    Row: {
      id: string
      owner_id: string
      session_id: string
      request_id: string
      fingerprint: string
      model: string
      created_at: string
      expires_at: string
      cost_micros: number
      status: string
      latency_ms: number | null
      input_tokens: number | null
      output_tokens: number | null
    }
    Insert: {
      id: string
      owner_id: string
      session_id: string
      request_id: string
      fingerprint: string
      model: string
      created_at?: string
      expires_at: string
      cost_micros: number
      status: string
      latency_ms?: number | null
      input_tokens?: number | null
      output_tokens?: number | null
    }
    Update: {
      id?: string
      owner_id?: string
      session_id?: string
      request_id?: string
      fingerprint?: string
      model?: string
      created_at?: string
      expires_at?: string
      cost_micros?: number
      status?: string
      latency_ms?: number | null
      input_tokens?: number | null
      output_tokens?: number | null
    }
    Relationships: []
  }
  ai_practice_lock: {
    Row: {
      id: boolean
    }
    Insert: {
      id?: boolean
    }
    Update: {
      id?: boolean
    }
    Relationships: []
  }
  ai_practice_sessions: {
    Row: {
      id: string
      owner_id: string
      created_at: string
    }
    Insert: {
      id: string
      owner_id: string
      created_at?: string
    }
    Update: {
      id?: string
      owner_id?: string
      created_at?: string
    }
    Relationships: []
  }
  assessment_events: {
    Row: {
      user_id: string
      id: string
      session_id: string
      question_index: number
      operation_id: string
      accepted_order: number
      recorded_at: string | null
      activity_date: string | null
      payload: Json
    }
    Insert: {
      user_id: string
      id: string
      session_id: string
      question_index: number
      operation_id: string
      accepted_order: number
      recorded_at?: string | null
      activity_date?: string | null
      payload: Json
    }
    Update: {
      user_id?: string
      id?: string
      session_id?: string
      question_index?: number
      operation_id?: string
      accepted_order?: number
      recorded_at?: string | null
      activity_date?: string | null
      payload?: Json
    }
    Relationships: []
  }
  builtin_overrides: {
    Row: {
      user_id: string
      vocabulary_id: string
      content: Json | null
      suppressed: boolean
      updated_at: string
      revision: number
    }
    Insert: {
      user_id: string
      vocabulary_id: string
      content?: Json | null
      suppressed?: boolean
      updated_at?: string
      revision?: number
    }
    Update: {
      user_id?: string
      vocabulary_id?: string
      content?: Json | null
      suppressed?: boolean
      updated_at?: string
      revision?: number
    }
    Relationships: []
  }
  hidden_builtin_vocabulary: {
    Row: {
      user_id: string
      vocabulary_id: number
      hidden: boolean
      archived_state: Json
      updated_at: string
      revision: number
    }
    Insert: {
      user_id: string
      vocabulary_id: number
      hidden?: boolean
      archived_state?: Json
      updated_at?: string
      revision?: number
    }
    Update: {
      user_id?: string
      vocabulary_id?: number
      hidden?: boolean
      archived_state?: Json
      updated_at?: string
      revision?: number
    }
    Relationships: []
  }
  learning_progress: {
    Row: {
      id: string
      user_id: string
      vocabulary_id: string
      vocabulary_source: string
      favorite: boolean
      learned: boolean
      needs_review: boolean
      times_tested: number
      times_known: number
      times_missed: number
      consecutive_known: number
      last_tested_at: string | null
      last_known_at: string | null
      next_review_at: string | null
      english_to_turkish_stats: Json
      turkish_to_english_stats: Json
      updated_at: string
      revision: number
    }
    Insert: {
      id?: string
      user_id: string
      vocabulary_id: string
      vocabulary_source: string
      favorite?: boolean
      learned?: boolean
      needs_review?: boolean
      times_tested?: number
      times_known?: number
      times_missed?: number
      consecutive_known?: number
      last_tested_at?: string | null
      last_known_at?: string | null
      next_review_at?: string | null
      english_to_turkish_stats?: Json
      turkish_to_english_stats?: Json
      updated_at?: string
      revision?: number
    }
    Update: {
      id?: string
      user_id?: string
      vocabulary_id?: string
      vocabulary_source?: string
      favorite?: boolean
      learned?: boolean
      needs_review?: boolean
      times_tested?: number
      times_known?: number
      times_missed?: number
      consecutive_known?: number
      last_tested_at?: string | null
      last_known_at?: string | null
      next_review_at?: string | null
      english_to_turkish_stats?: Json
      turkish_to_english_stats?: Json
      updated_at?: string
      revision?: number
    }
    Relationships: []
  }
  migration_receipts: {
    Row: {
      user_id: string
      id: string
      operation_id: string
      created_at: string
    }
    Insert: {
      user_id: string
      id: string
      operation_id: string
      created_at?: string
    }
    Update: {
      user_id?: string
      id?: string
      operation_id?: string
      created_at?: string
    }
    Relationships: []
  }
  operation_receipts: {
    Row: {
      user_id: string
      id: string
      created_at: string
    }
    Insert: {
      user_id: string
      id: string
      created_at?: string
    }
    Update: {
      user_id?: string
      id?: string
      created_at?: string
    }
    Relationships: []
  }
  profiles: {
    Row: {
      id: string
      created_at: string
      revision: number
      sync_protocol: number
      reset_epoch: number
    }
    Insert: {
      id: string
      created_at?: string
      revision?: number
      sync_protocol?: number
      reset_epoch?: number
    }
    Update: {
      id?: string
      created_at?: string
      revision?: number
      sync_protocol?: number
      reset_epoch?: number
    }
    Relationships: []
  }
  test_answers: {
    Row: {
      id: string
      user_id: string
      session_id: string
      vocabulary_id: string
      vocabulary_source: string
      direction: string
      typed_answer: string
      was_correct: boolean
      self_assessment_known: boolean
      answered_at: string | null
      activity_date: string | null
      question_index: number
      operation_id: string
      snapshot: Json
    }
    Insert: {
      id?: string
      user_id: string
      session_id: string
      vocabulary_id: string
      vocabulary_source: string
      direction: string
      typed_answer: string
      was_correct: boolean
      self_assessment_known: boolean
      answered_at?: string | null
      activity_date?: string | null
      question_index: number
      operation_id: string
      snapshot: Json
    }
    Update: {
      id?: string
      user_id?: string
      session_id?: string
      vocabulary_id?: string
      vocabulary_source?: string
      direction?: string
      typed_answer?: string
      was_correct?: boolean
      self_assessment_known?: boolean
      answered_at?: string | null
      activity_date?: string | null
      question_index?: number
      operation_id?: string
      snapshot?: Json
    }
    Relationships: []
  }
  test_sessions: {
    Row: {
      id: string
      user_id: string
      session_type: string
      test_direction: string
      started_at: string | null
      completed_at: string | null
      total_questions: number
      known_count: number
      missed_count: number
      accuracy: number
      state: Json
      updated_at: string
      revision: number
      archived_at: string | null
    }
    Insert: {
      id: string
      user_id: string
      session_type: string
      test_direction: string
      started_at?: string | null
      completed_at?: string | null
      total_questions: number
      known_count?: number
      missed_count?: number
      accuracy?: number
      state: Json
      updated_at?: string
      revision?: number
      archived_at?: string | null
    }
    Update: {
      id?: string
      user_id?: string
      session_type?: string
      test_direction?: string
      started_at?: string | null
      completed_at?: string | null
      total_questions?: number
      known_count?: number
      missed_count?: number
      accuracy?: number
      state?: Json
      updated_at?: string
      revision?: number
      archived_at?: string | null
    }
    Relationships: []
  }
  user_vocabulary: {
    Row: {
      id: string
      user_id: string
      english: string
      english_alternatives: string[]
      turkish_meanings: string[]
      part_of_speech: string | null
      example_sentence: string | null
      tags: string[]
      created_at: string | null
      updated_at: string
      revision: number
      deleted_at: string | null
    }
    Insert: {
      id: string
      user_id: string
      english: string
      english_alternatives?: string[]
      turkish_meanings: string[]
      part_of_speech?: string | null
      example_sentence?: string | null
      tags?: string[]
      created_at?: string | null
      updated_at?: string
      revision?: number
      deleted_at?: string | null
    }
    Update: {
      id?: string
      user_id?: string
      english?: string
      english_alternatives?: string[]
      turkish_meanings?: string[]
      part_of_speech?: string | null
      example_sentence?: string | null
      tags?: string[]
      created_at?: string | null
      updated_at?: string
      revision?: number
      deleted_at?: string | null
    }
    Relationships: []
  }
}; Views: Record<string,never>; Functions: {
 kelime_snapshot_v5: { Args: Record<string,never>; Returns: Json }
 kelime_apply_v5: { Args: { p_operation: Json }; Returns: Json }
 kelime_reconcile_v5: { Args: { p_ids: string[] }; Returns: Json }
 kelime_compact_drafts_v5: { Args: { p_operations: Json; p_batch: string }; Returns: Json }
 kelime_snapshot_v2: { Args: Record<string,never>; Returns: Json }
 kelime_apply_v2: { Args: { p_operation: Json }; Returns: Json }
 kelime_snapshot_v3: { Args: Record<string,never>; Returns: Json }
 kelime_apply_v3: { Args: { p_operation: Json }; Returns: Json }
 kelime_snapshot_v4: { Args: Record<string,never>; Returns: Json }
 kelime_reconcile: { Args: { p_ids: string[] }; Returns: Json }
 kelime_compact_drafts: { Args: { p_operations: Json; p_batch: string }; Returns: Json }
 kelime_apply_v4: { Args: { p_operation: Json }; Returns: Json }
 kelime_snapshot: { Args: Record<string,never>; Returns: Json }
 kelime_apply: { Args: { p_operation: Json }; Returns: Json }
}; Enums: Record<string,never>; CompositeTypes: Record<string,never> } }
